version: '3'

services:

  frontend_one:
    build:
      context: ./frontend
    container_name: frontend_one
    restart: always
    environment:
      - PORT=3000
      - NAME="NAME"
      - SERVER_NUMBER=1
  

  frontend_two:
    build:
      context: ./frontend
    container_name: frontend_two
    restart: always
    environment:
      - PORT=3000
      - NAME="NAME"
      - SERVER_NUMBER=2
  
  
  ghost:
    image: ghost:4
    restart: always
    depends_on:
      - db
    environment:
      url: https://shishirsudhaman.com/blog
      database__client: mysql
      database__connection__host: db
      database__connection__user: root
      database__connection__password: example
      database__connection__database: ghost
    volumes:
      - ./data/ghost/:/var/lib/ghost/content
  
  
  db:
    image: mysql:5.7
    restart: always
    environment:
      - MYSQL_ROOT_PASSWORD=example
    volumes:
      - ./data/mysql:/var/lib/mysql
      
  
  nginx:
    container_name: nginx_container
    build:
      context: ./nginx
    restart: always
    depends_on:
      - frontend
    ports:
      - "80:80"
      - "443:443"
    volumes:
       - /etc/letsencrypt/:/etc/letsencrypt/
       - /usr/share/nginx/html:/usr/share/nginx/html
